production: &vcap
  sessions:
    default:
      database: <%= JSON.parse( ENV['VCAP_SERVICES'] )['my-mongodb'].first['credentials']['db'] rescue '' %>
      username: <%= JSON.parse( ENV['VCAP_SERVICES'] )['my-mongodb'].first['credentials']['username'] rescue '' %>
      password: <%= JSON.parse( ENV['VCAP_SERVICES'] )['my-mongodb'].first['credentials']['password'] rescue '' %>
      hosts:
        <%= ("- #{JSON.parse( ENV['VCAP_SERVICES'] )['my-mongodb'].first['credentials']['hostname']}:#{JSON.parse( ENV['VCAP_SERVICES'] )['my-mongodb'].first['credentials']['port']}") rescue ''%>
      options:
        pool_size: 35
        timeout: 20
        pool_timeout: 5
  options:
    raise_not_found_error: false

staging:
  <<: *vcap

development:
  sessions:
    default:
      database: videoapp_development
      hosts:
        - 127.0.0.1:27017
      options:
        pool_size: 35
        timeout: 20
        pool_timeout: 5
  options:
    raise_not_found_error: false
test:
  sessions:
    default:
      database: videoapp_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
